### ISSUE TITLE
how send a audio/video?

### ISSUE THREAD

**Issue by theolm** [jmendeth/node-botgram#4]
how can i make the bot send an audio file or a video (that already are in telegram servers) to a group?

**Comment by jmendeth** [comment]
When a file is uploaded to Telegram servers, it gets assigned a unique ID, such as `BQADAgAD3gAD9HsZAAFphGBFqImfGAI`. Simply pass that ID when sending:

~~~ javascript
reply.sticker("BQADAgAD3gAD9HsZAAFphGBFqImfGAI");
reply.video("...");
// ...
~~~

Look [here](https://github.com/jmendeth/node-botgram/blob/master/lib/reply.js#L109) for how to send all kinds of messages, until docs are finished. If you don't know the ID of your file, you can run the [`print` example](https://github.com/jmendeth/node-botgram/blob/master/examples/print.js).

**Important:** The ID has to be used in the *same context* the file was uploaded. For instance, if the ID belongs to an image uploaded as photo, it can't be passed to `reply.document()`. You'd need to reupload in that case.

**Comment by theolm** [comment]
wow.
thanks for the quick reply.
you did a really good job with this framework. 
congrats dude!

**Comment by jmendeth** [comment]
Most documentation finished now, see [messages sending](https://github.com/jmendeth/node-botgram/blob/master/docs/reply.md#message-sending) and the [section on uploading files](https://github.com/jmendeth/node-botgram/blob/master/docs/reply.md#uploading-files).
Closing the issue now, reopen if you see anything wrong.
