### ISSUE TITLE
Question: Actively sending messages

### ISSUE THREAD

**Issue by twinone** [jmendeth/node-botgram#5]
What would be the correct approach to implement a personal assistant-like bot that after the /start command waits for an external event (such as a weather update) and notifies the owner's chat? After a server reboot, how can I send pending messages to the owner's chat? Is there some way to save the chat ID?

**Comment by jmendeth** [comment]
You can send messages anytime by using [`bot.reply(id)`](https://github.com/jmendeth/node-botgram/blob/master/docs/reply.md#getting-a-queue-manually), i.e.:

~~~ js
var reply = bot.reply(205023012);
reply.text("hi");
~~~

Conditions and limits apply, see link.

---

`msg.chat.id` can be used to retrieve the ID of the chat the message was sent to.

**Comment by twinone** [comment]
Awesome! Maybe it's something worth mentioning in the index page of the documentation?

**Comment by jmendeth** [comment]
Mmm in the tutorial... I'll think about it.
