### ISSUE TITLE
msg.args() is not intuitive

### ISSUE THREAD

**Issue by twinone** [jmendeth/node-botgram#9]
It's weird behavior that the following command:
`/cmd`

`msg.args()` returns "" correctly, but when you try to split it, `msg.args(2)` returns `['']`. It should return `[]`, as there are no arguments.

**Comment by jmendeth** [comment]
That behaviour is consistent with `String#split(...)`.
Yeah, I suppose it would be more intuitive to return `[]`, I'll change it.

**Comment by twinone** [comment]
Just realized -- maybe it's an idea to keep the msg.args() consistent with string.split() and provide a msg.argv as an array with the intuitive argument list?

**Comment by jmendeth** [comment]
No, I think this is good.
`msg.args(N)` could be understood as `msg.text.split(" ").slice(1)`,
so if `msg.text = "/cmd"` it makes sense to return `[]`.
